# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing yarn
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running Jest Tests
          command: yarn run test

  codacy:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing yarn
          command: yarn install
      - run:
          name: Installing Codacy
          command: yarn add codacy-coverage --save
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Sending Coverage Data to Codacy
          command: yarn run codacy

  deploy:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing yarn
          command: yarn install
      - run:
          name: Installing exp
          command: yarn add exp
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Signing Into Expo
          command: yarn run exp login --username ndsmith --password ad4jkj2hd
      - run:
          name: Deploying to Expo
          command: yarn run exp publish

workflows:
  version: 2
  test-codacy-deploy:
    jobs:
      - test
      - codacy:
          requires:
            - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master